---
- hosts: all
  roles:
    - vagrant
  vars:
    mysql_databases:
      - name: my_db
        import_file: sql/my_db.sql
    mysql_users:
      - name: my_user
        password: "very LONG s3cr3t password"
        privileges: "my_db.*:ALL"
