---
- name: ensure mariadb upstream repository key is added
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ mysql_apt_key }}"

- name: ensure mariadb upstream repository is configured
  apt_repository:
    repo: "deb [arch=amd64] http://mirrors.n-ix.net/mariadb/repo/{{ mysql_upstream_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
